### ISSUE TITLE
Aggiornare file README.md

### ISSUE THREAD

**Issue by domenicomonaco** [Florian-Bool-65/git-team#8]
Aggiornare il file [README.md](https://github.com/Florian-Bool-65/git-team/blob/master/README.md) del progetto 

**eliminare tutte la parte di default sostituendole con i passi da seguire per installare il progetto**

## Informazioni da inserire 
- [ ] requisiti php
- [ ] come clonare
- [x] installazione progetto
- [ ] eventuali problemi
- [x] eventuali migration / seedeer

**Comment by dulcetiseduce1** [comment]
issue parzialmente svolta 
commit fatto, ho creato la pull request
